"""Added null to user_friend_association_table

Revision ID: 3157f3b797d7
Revises: ee9d4f8d05d1
Create Date: 2024-05-05 20:08:01.933487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3157f3b797d7'
down_revision: Union[str, None] = 'ee9d4f8d05d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_friend_association_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_friend_association_table', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_friend_association_table', 'friend_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_friend_association_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
